version: '3.8'

services:
  hmdm:
    build: 
      context: .
      dockerfile: Dockerfile.coolify
    container_name: hmdm-app
    environment:
      - DB_HOST=qkgwosowcss0go40oc00oswo
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=28DmoIQOAspmJ5t7sDEJ5YWlu6h8MkKB0ia4rPqRHF6WKQ4o9ZdUNSClHgPC3gxC
      - DOMAIN=${DOMAIN:-localhost}
      - EMAIL=${EMAIL:-admin@example.com}
      - JAVA_OPTS=${JAVA_OPTS:--Xms512m -Xmx1024m}
      - COOLIFY_DEPLOYMENT=true
    volumes:
      - hmdm_data:/opt/hmdm
      - tomcat_data:/var/lib/tomcat9
      - tomcat_logs:/var/log/tomcat9
    restart: unless-stopped
    # Temporarily disabled to debug startup
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
    #   interval: 30s
    #   timeout: 15s
    #   retries: 10
    #   start_period: 240s
    labels:
      # Coolify labels for automatic SSL and domain configuration
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.hmdm.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.hmdm.entrypoints=websecure"
      - "traefik.http.routers.hmdm.tls.certresolver=letsencrypt"
      - "traefik.http.services.hmdm.loadbalancer.server.port=8080"
      - "traefik.http.routers.hmdm-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.hmdm-http.entrypoints=web"
      - "traefik.http.routers.hmdm-http.middlewares=redirect-to-https"

volumes:
  hmdm_data:
    driver: local
  tomcat_data:
    driver: local
  tomcat_logs:
    driver: local

networks:
  hmdm-network:
    driver: bridge 